#!/bin/bash

folder="/root/workspace.docker_branch/TestSuite-Konnektor-T-Systems/TestFallSteuerung/Protokollierung/"
folder="/root/Musik/Protokollierung/"

index=1
passed=0
failed=0

filename=$(date)".log"

#version="1_5_0"
source /root/workspace.docker_branch/TestSuite-Konnektor-T-Systems/testSteuerungsConfig.sh
echo ""
###echo $EXECUTION_MODUS
echo ""
#EXECUTION_MODUS=EXECUTION_1_5_0_b209_OpenLimit
#EXECUTION_MODUS=EXECUTION_1_4_13_b7_CampusX
#echo ""
#echo $EXECUTION_MODUS




PWD_BKUP=$(pwd)
cd $folder
pwd
tests=$(grep -r "Verdict für den Gesamt-Testfall: PASSED" . | grep $EXECUTION_MODUS | grep ".txt"| cut -d '/' -f 3)
#tests=$(grep -r "Verdict für den Gesamt-Testfall: PASSED" "$folder" | grep $EXECUTION_MODUS | grep ".txt"| cut -d '/' -f 6) 
#tests=$(grep -r "Verdict für den Gesamt-Testfall: PASSED" "$folder" | grep $EXECUTION_MODUS | grep ".txt")

#	GS_A_5078_01



cd $PWD_BKUP
echo $tests>tests.txt






while read p; do
  index=$(( $index + 1 ))
  #echo "${p}"
  value=${p}
  #echo "$value"
  cat tests.txt | grep "$value" &>/dev/null
  if [ $? -ne 0 ];then
     echo "$index   $value   FAILED"
     failed=$(( $failed + 1 ))
     if [ "$1" = "log" ]
     then
       echo "$index   $value   FAILED">>"$filename"
     fi
  else
     echo "$index   $value   PASSED"
     passed=$(( $passed + 1 ))
     if [ "$1" = "log" ]
      then
        echo "$index   $value   PASSED">>"$filename"
      fi
     fi

#  grep -r "Verdict für den Gesamt-Testfall: PASSED" | grep "${p}" #| grep ".txt" | cut -d '/' -f 2 
done < tf_list

echo ""
echo ""
echo "PASSED:  $passed"
echo ""
echo "FAILED:  $failed"
echo ""
echo ""
echo ""
echo ""
echo "$1"
echo "$2"
















